Update hdf5io.py to be compatible with new numpy versions
```
AttributeError: `np.unicode_` was removed in the NumPy 2.0 release. Use `np.str_` instead.
```